# Site settings
title: John Michael Fischer
email: johnmichael.fischer+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An outlet for cataloging and sharing my activities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whiskeybravo.github.io" # the base hostname & protocol for your site
twitter_username: WalkingWhiskey
github_username:  WhiskeyBravo

#github required
safe: true
lsi: false

# Use Redcarpet as markdown generator as this is GitHub standard, makes the 
# composer preview match the generated output.
markdown: redcarpet

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty