# Site settings
title: John Michael Fischer
email: johnmichael.fischer+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An outlet for cataloging and sharing my activities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whiskeybravo.github.io" # the base hostname & protocol for your site
twitter_username: WalkingWhiskey
github_username:  WhiskeyBravo

# Build settings
markdown: kramdown

#github required
safe: true
lsi: false